FROM mcr.microsoft.com/mssql/server:2022-latest

COPY --chown=mssql:root sql/ /usr/src/sql/

USER root
RUN mkdir -p /var/opt/mssql/backups && chown mssql:root /var/opt/mssql/backups && chmod 2770 /var/opt/mssql/backups
USER mssql

EXPOSE 1433
