import {emptyDesign,validateDesign,designSQL} from './lib/designer-model.js';
const panel=addWorkspace('designer','✎ Конструктор БД');
$('diagram-tab')?.after($('designer-tab'));
panel.innerHTML=`<div class="section-toolbar"><div><h2>Конструктор базы данных</h2><p class="muted">Ручной проект · изменения на холсте не применяются к базе</p></div><div class="actions"><button class="button" id="design-new">Новый</button><button class="button" id="design-open">Открыть…</button><button class="button primary" id="design-save">Сохранить</button></div></div><div class="design-toolbar"><label>Проект <input id="design-name" value="Новый проект" maxlength="120"></label><button class="button" id="design-table">＋ Таблица</button><button class="button" id="design-link">↗ Связь</button><button class="button" id="design-note">＋ Заметка</button><button class="button" id="design-undo" title="Ctrl / ⌘ Z">↶</button><button class="button" id="design-redo" title="Ctrl / ⌘ Shift Z">↷</button><button class="button" id="design-fit">Вместить</button><button class="button" id="design-minus">−</button><output id="design-zoom">100%</output><button class="button" id="design-plus">＋</button><button class="button" id="design-sql">SQL…</button><button class="button" id="design-json">↓ JSON</button><button class="button" id="design-import">↑ JSON</button><button class="button" id="design-svg-export">↓ SVG</button><button class="button" id="design-fullscreen">На весь экран</button></div><p id="design-status" class="muted" role="status"></p><div class="design-workspace"><div id="design-viewport" tabindex="0" aria-label="Холст конструктора: перетаскивайте таблицы, колесо меняет масштаб"><svg id="design-svg" xmlns="http://www.w3.org/2000/svg" role="group" aria-label="Редактируемая схема базы данных"></svg><p class="design-empty" id="design-empty">Добавьте первую таблицу кнопкой «＋ Таблица».<br>Тяните кружок у столбца родителя к столбцу дочерней таблицы, чтобы создать FK.</p></div><aside id="design-inspector" aria-label="Свойства выбранного элемента"></aside></div><p class="muted">Фон — перемещение холста · заголовок — перемещение таблицы · двойной щелчок по фону — новая таблица · кружки у столбцов — FK · пунктир — свободная связь · Delete — удалить · Ctrl/⌘ Z — отменить</p>`;
const svg=$('design-svg'),viewport=$('design-viewport'),inspector=$('design-inspector'),NS='http://www.w3.org/2000/svg',W=300,H=44,R=27;
let model=emptyDesign(),name='Новый проект',project=null,saved='',selection=null,undo=[],redo=[],zoom=1,pan={x:30,y:30},gesture=null,saving=false,linkStart=null;
const uid=()=>crypto.randomUUID(),snapshot=()=>JSON.stringify({name,model});
const changed=()=>snapshot()!==saved;
function status(message){$('design-status').textContent=message||`${project?'Сохранённый проект':'Новый проект'} · ${model.tables.length} таблиц · ${model.relations.length} связей${changed()?' · Есть несохранённые изменения':''}`;$('design-undo').disabled=!undo.length;$('design-redo').disabled=!redo.length;$('design-save').disabled=saving;}
function draft(){try{localStorage.setItem('studio.designer.draft.v1',JSON.stringify({model,name,project,saved}));}catch{status('Черновик не помещается в браузер. Сохраните проект в Studio или скачайте JSON.');}}
function commit(before){if(before===snapshot())return;undo.push(before);if(undo.length>60)undo.shift();redo=[];draft();render();}
function update(action){const before=snapshot();try{action();model=validateDesign(model);commit(before);}catch(e){const old=JSON.parse(before);model=old.model;name=old.name;notice(e.message,true);render();}}
function replace(next,nextName,meta=null){if(saving)throw new Error('Дождитесь сохранения.');model=validateDesign(next);name=nextName;project=meta;saved=meta?snapshot():'';selection=null;undo=[];redo=[];draft();render();fit();}
function discardThen(action){if(saving)throw new Error('Дождитесь сохранения.');if(changed()&&(model.tables.length||model.notes.length))modal('Заменить текущий черновик','<p>Несохранённые изменения будут заменены. Можно закрыть это окно и сначала сохранить проект или скачать JSON.</p>',action,'Заменить');else return action();}
function node(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;}
const height=t=>H+Math.max(1,t.columns.length)*R+10;
function point(t,column,side){const i=t.columns.findIndex(c=>c.id===column);return {x:t.x+(side==='right'?W:0),y:t.y+(i<0?H/2:H+i*R+R/2)};}
function pathFor(r){const p=model.tables.find(t=>t.id===r.parent),c=model.tables.find(t=>t.id===r.child),a=point(p,r.columns[0]?.parent,p===c||c.x>=p.x?'right':'left'),b=point(c,r.columns[0]?.child,p===c||c.x<p.x?'right':'left');if(p===c)return `M ${a.x} ${a.y} C ${a.x+100} ${a.y-65},${b.x+100} ${b.y+80},${b.x} ${b.y}`;const middle=(a.x+b.x)/2;return `M ${a.x} ${a.y} C ${middle} ${a.y},${middle} ${b.y},${b.x} ${b.y}`;}
function paint(){
 svg.replaceChildren();const defs=node('defs'),pattern=node('pattern',{id:'design-grid',width:24,height:24,patternUnits:'userSpaceOnUse',patternTransform:`translate(${pan.x} ${pan.y}) scale(${zoom})`});pattern.append(node('circle',{cx:1,cy:1,r:1,fill:'var(--line)'}));defs.append(pattern);const marker=node('marker',{id:'design-arrow',viewBox:'0 0 10 10',refX:10,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'});marker.append(node('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'var(--blue)'}));defs.append(marker);svg.append(defs,node('rect',{width:'100%',height:'100%',fill:'url(#design-grid)'}));const scene=node('g',{transform:`translate(${pan.x} ${pan.y}) scale(${zoom})`,'data-scene':''});svg.append(scene);
 for(const r of model.relations){const g=node('g',{'data-relation':r.id,class:'design-edge'+(selection===r.id?' selected':''),tabindex:0,role:'button','aria-label':'Связь '+(r.name||r.kind)}),d=pathFor(r);g.append(node('path',{d,class:'design-edge-hit'}),node('path',{d,class:'design-edge-line','stroke-dasharray':r.kind==='association'?'7 5':'','marker-end':'url(#design-arrow)'}));const p=model.tables.find(t=>t.id===r.parent),c=model.tables.find(t=>t.id===r.child);g.append(node('text',{x:p===c?p.x+W+15:(p.x+c.x+W)/2,y:p===c?p.y-15:(p.y+c.y)/2+H/2-9,class:'design-edge-label'},r.name|| (r.kind==='fk'?'FK':'Связь')));scene.append(g);}
 for(const t of model.tables){const g=node('g',{transform:`translate(${t.x} ${t.y})`,'data-table':t.id,class:'design-table'+(selection===t.id?' selected':''),tabindex:0,role:'button','aria-label':t.schema+'.'+t.name});g.append(node('rect',{width:W,height:height(t),rx:9,class:'design-table-body'}),node('path',{d:`M 9 0 H ${W-9} Q ${W} 0 ${W} 9 V ${H} H 0 V 9 Q 0 0 9 0`,class:'design-table-header'}),node('text',{x:14,y:28,class:'design-title'},(t.schema+'.'+t.name).slice(0,31)));
 for(const [i,c] of t.columns.entries()){const y=H+i*R;g.append(node('line',{x1:1,x2:W-1,y1:y,y2:y,class:'design-divider'}),node('text',{x:14,y:y+18,class:'design-key'},c.primaryKey?'PK':c.unique?'UK':model.relations.some(r=>r.kind==='fk'&&r.child===t.id&&r.columns.some(p=>p.child===c.id))?'FK':''),node('text',{x:40,y:y+18,class:'design-column'},c.name.slice(0,18)),node('text',{x:W-15,y:y+18,'text-anchor':'end',class:'design-type'},c.type.slice(0,18)+(c.nullable&&!c.primaryKey?' ?':'')));
 for(const x of [0,W])g.append(node('circle',{cx:x,cy:y+R/2,r:5,'data-port':c.id,'data-port-table':t.id,class:'design-port',tabindex:0,role:'button','aria-label':`Соединить ${t.name}.${c.name}`}));}
 scene.append(g);}
 for(const n of model.notes){const lines=n.text.split('\n').flatMap(line=>line.match(/.{1,31}/g)||['']).slice(0,10),g=node('g',{transform:`translate(${n.x} ${n.y})`,'data-note':n.id,class:'design-note'+(selection===n.id?' selected':''),tabindex:0,role:'button','aria-label':'Заметка'});g.append(node('rect',{width:250,height:Math.max(90,lines.length*20+30),rx:7}));lines.forEach((line,i)=>g.append(node('text',{x:14,y:28+i*20},line)));scene.append(g);}
 $('design-empty').hidden=!!(model.tables.length||model.notes.length);$('design-zoom').textContent=Math.round(zoom*100)+'%';
}
function render(){paint();inspect();$('design-name').value=name;status();}
function inspect(){
 const t=model.tables.find(t=>t.id===selection),r=model.relations.find(r=>r.id===selection),n=model.notes.find(n=>n.id===selection);
 if(!t&&!r&&!n){inspector.innerHTML='<h3>Свойства элемента</h3><p class="muted">Нажмите таблицу, связь или заметку. Положение таблиц можно менять перетаскиванием.</p><p class="muted">Проект сохраняется отдельно от баз. SQL можно проверить и скачать кнопкой «SQL…».</p>';return;}
 inspector.innerHTML=`<h3>${t?'Таблица':r?'Связь':'Заметка'}</h3><p>${esc(t?t.schema+'.'+t.name:r?r.name||r.kind:n.text.slice(0,80))}</p><button class="button" id="design-edit">Изменить</button> <button class="button danger" id="design-delete">Удалить</button>${t?`<h3>Столбцы</h3>${t.columns.map(c=>`<div class="design-column-info"><strong>${esc(c.name)}</strong><small>${esc(c.type)}${c.primaryKey?' · PK':''}${c.identity?' · AUTO':''}${c.unique?' · UNIQUE':''}${c.nullable&&!c.primaryKey?' · NULL':''}</small></div>`).join('')}`:r?`<p class="muted">${r.kind==='fk'?'Внешний ключ':'Свободная связь, без SQL'}</p>${r.columns.map(pair=>{const p=model.tables.find(t=>t.id===r.parent),c=model.tables.find(t=>t.id===r.child);return '<p>'+esc(p.name+'.'+p.columns.find(c=>c.id===pair.parent).name)+' → '+esc(c.name+'.'+c.columns.find(c=>c.id===pair.child).name)+'</p>';}).join('')}`:''}`;
 $('design-edit').onclick=safe(()=>t?editTable(t):r?editRelation(r):editNote(n));$('design-delete').onclick=safe(deleteSelected);
}
function deleteSelected(){if(!selection)return;const id=selection;update(()=>{model.tables=model.tables.filter(t=>t.id!==id);model.notes=model.notes.filter(n=>n.id!==id);model.relations=model.relations.filter(r=>r.id!==id&&r.parent!==id&&r.child!==id);selection=null;});}
function newTable(position){const count=model.tables.length+1;let candidate='Table'+count;while(model.tables.some(t=>t.name===candidate))candidate+='New';const t={id:uid(),schema:'dbo',name:candidate,x:position?.x??(40+((count-1)%4)*40-pan.x)/zoom,y:position?.y??(50+((count-1)%4)*40-pan.y)/zoom,columns:[{id:uid(),name:'Id',type:'INT',primaryKey:true,identity:true,nullable:false,unique:false}]};update(()=>{model.tables.push(t);selection=t.id;});editTable(t);}
function editTable(table){
 modal('Таблица проекта',field('schema','Схема',table.schema)+field('name','Название',table.name)+'<p class="muted">PK можно отметить у нескольких столбцов. Порядок строк задаёт порядок составного PK. Неполный проект можно сохранить; типы и связи проверяются при экспорте SQL. Удаление столбца удаляет затронутые связи проекта; действие можно отменить.</p><div id="design-columns"></div><button type="button" class="button" id="design-add-column">＋ Столбец</button>',async form=>{const v=formValues(form),columns=[...$('design-columns').children].map(row=>({id:row.dataset.id,name:row.querySelector('[data-name]').value,type:row.querySelector('[data-type]').value,primaryKey:row.querySelector('[data-pk]').checked,unique:row.querySelector('[data-unique]').checked,identity:row.querySelector('[data-identity]').checked,nullable:row.querySelector('[data-null]').checked}));const next=structuredClone(model),t=next.tables.find(t=>t.id===table.id);Object.assign(t,{name:v.name,schema:v.schema,columns});const ids=new Set(columns.map(c=>c.id));next.relations=next.relations.filter(r=>!(r.parent===t.id&&r.columns.some(p=>!ids.has(p.parent)))&&!(r.child===t.id&&r.columns.some(p=>!ids.has(p.child))));validateDesign(next);update(()=>{model=next;});},'Применить к проекту',false,true);
 function row(c){const el=document.createElement('div');el.className='design-column-form';el.dataset.id=c.id;el.innerHTML=`<input data-name aria-label="Название столбца" value="${esc(c.name)}" maxlength="128"><input data-type aria-label="SQL-тип" list="design-type-options" value="${esc(c.type)}" placeholder="NVARCHAR(255)"><label><input data-pk type="checkbox" ${c.primaryKey?'checked':''}> PK</label><label><input data-unique type="checkbox" ${c.unique?'checked':''}> UK</label><label><input data-identity type="checkbox" ${c.identity?'checked':''}> AUTO</label><label><input data-null type="checkbox" ${c.nullable?'checked':''}> NULL</label><button type="button" class="icon-button" data-up aria-label="Столбец выше">↑</button><button type="button" class="icon-button" data-remove aria-label="Удалить столбец">×</button>`;el.querySelector('[data-remove]').onclick=()=>el.remove();el.querySelector('[data-up]').onclick=()=>{if(el.previousElementSibling)el.previousElementSibling.before(el);};for(const flag of ['pk','identity'])el.querySelector('[data-'+flag+']').onchange=()=>{if(el.querySelector('[data-'+flag+']').checked)el.querySelector('[data-null]').checked=false;};$('design-columns').append(el);}
 table.columns.forEach(row);$('design-add-column').onclick=()=>{if($('design-columns').children.length>=50)return;row({id:uid(),name:'Column'+($('design-columns').children.length+1),type:'NVARCHAR(255)',nullable:true});};const dl=document.createElement('datalist');dl.id='design-type-options';dl.innerHTML=['INT','BIGINT','BIT','NVARCHAR(255)','VARCHAR(255)','DECIMAL(18,2)','DATE','DATETIME2','UNIQUEIDENTIFIER','VARBINARY(MAX)'].map(t=>`<option value="${t}">`).join('');$('modal-body').append(dl);
}
function editNote(note){modal('Заметка','<label class="field">Текст<textarea name="text" rows="8" maxlength="4000">'+esc(note.text)+'</textarea></label>',async form=>{const value=formValues(form).text;update(()=>{model.notes.find(n=>n.id===note.id).text=value;});},'Применить');}
function editRelation(relation,initial={}){
 if(!model.tables.length)throw new Error('Сначала добавьте таблицы.');const draft=relation?structuredClone(relation):{id:uid(),kind:'fk',name:'',parent:initial.parent||model.tables[0].id,child:initial.child||model.tables.at(-1).id,columns:[],onDelete:'NO ACTION',onUpdate:'NO ACTION'};
 const tables=model.tables.map(t=>({value:t.id,label:t.schema+'.'+t.name}));
 modal('Связь проекта',field('name','Название',draft.name)+selectField('kind','Вид',[{value:'fk',label:'Внешний ключ (FK)'},{value:'association',label:'Свободная связь / пояснение'}],draft.kind)+selectField('parent','Родитель',tables,draft.parent)+selectField('child','Дочерняя таблица',tables,draft.child)+'<p class="muted">Для FK выберите полный PK или один UNIQUE-столбец родителя. «Новый столбец» создаёт дочернее поле подходящего типа без AUTO.</p><div id="design-pairs"></div><button type="button" class="button" id="design-add-pair">＋ Пара столбцов</button>'+selectField('onDelete','При удалении',['NO ACTION','CASCADE','SET NULL'],draft.onDelete)+selectField('onUpdate','При обновлении',['NO ACTION','CASCADE','SET NULL'],draft.onUpdate),async form=>{
  const v=formValues(form),next=structuredClone(model),p=next.tables.find(t=>t.id===v.parent),c=next.tables.find(t=>t.id===v.child),pairs=[];
  if(v.kind==='fk')for(const row of $('design-pairs').children){const parent=p.columns.find(c=>c.id===row.querySelector('[data-parent-column]').value);if(!parent)throw new Error('Выберите родительский столбец.');let child=row.querySelector('[data-child-column]').value;
   if(child==='new'){const base=(p.name+'_'+parent.name).slice(0,120);let cname=base,suffix=2;while(c.columns.some(c=>c.name.toLowerCase()===cname.toLowerCase()))cname=base+'_'+suffix++;const col={id:uid(),name:cname,type:parent.type,primaryKey:false,identity:false,unique:false,nullable:true};c.columns.push(col);child=col.id;}
   pairs.push({parent:parent.id,child});}
  const r={id:draft.id,kind:v.kind,name:v.name,parent:v.parent,child:v.child,columns:pairs,onDelete:v.onDelete,onUpdate:v.onUpdate};if(relation)next.relations=next.relations.map(x=>x.id===r.id?r:x);else next.relations.push(r);validateDesign(next);update(()=>{model=next;selection=r.id;});
 },'Применить к проекту',false,true);
 const form=$('modal-form');function row(pair={}){const p=model.tables.find(t=>t.id===form.elements.parent.value),c=model.tables.find(t=>t.id===form.elements.child.value),el=document.createElement('div');el.className='design-pair';el.innerHTML=`<select data-parent-column aria-label="Родительский столбец">${p.columns.map(col=>`<option value="${col.id}" ${col.id===pair.parent?'selected':''}>${esc(col.name+' · '+col.type)}</option>`).join('')}</select><span>→</span><select data-child-column aria-label="Дочерний столбец"><option value="new">＋ Новый столбец</option>${c.columns.map(col=>`<option value="${col.id}" ${col.id===pair.child?'selected':''}>${esc(col.name+' · '+col.type)}</option>`).join('')}</select><button type="button" class="button">×</button>`;el.querySelector('button').onclick=()=>el.remove();$('design-pairs').append(el);}
 function reset(){ $('design-pairs').replaceChildren();const p=model.tables.find(t=>t.id===form.elements.parent.value);const pk=p.columns.filter(c=>c.primaryKey);(pk.length?pk:[p.columns[0]]).filter(Boolean).forEach(c=>row({parent:c.id}));}
 form.elements.parent.onchange=reset;form.elements.child.onchange=reset;form.elements.kind.onchange=()=>{$('design-pairs').hidden=$('design-add-pair').hidden=form.elements.kind.value!=='fk';};form.elements.kind.onchange();$('design-add-pair').onclick=()=>{if($('design-pairs').children.length<16)row();};if(draft.columns.length)draft.columns.forEach(row);else if(initial.parentColumn){const parent=model.tables.find(t=>t.id===initial.parent),pk=parent.columns.filter(c=>c.primaryKey);if(pk.length>1&&pk.some(c=>c.id===initial.parentColumn))pk.forEach(c=>row({parent:c.id,child:c.id===initial.parentColumn?initial.childColumn:undefined}));else row({parent:initial.parentColumn,child:initial.childColumn});}else reset();
}
function localPoint(e){const b=viewport.getBoundingClientRect();return {x:(e.clientX-b.left-pan.x)/zoom,y:(e.clientY-b.top-pan.y)/zoom};}
function fit(){const items=[...model.tables.map(t=>({x:t.x,y:t.y,w:W,h:height(t)})),...model.notes.map(n=>({...n,w:250,h:230}))];if(!items.length){zoom=1;pan={x:30,y:30};paint();return;}const left=Math.min(...items.map(t=>t.x)),top=Math.min(...items.map(t=>t.y)),right=Math.max(...items.map(t=>t.x+t.w)),bottom=Math.max(...items.map(t=>t.y+t.h));zoom=Math.max(.15,Math.min(1.4,(viewport.clientWidth-70)/(right-left),(viewport.clientHeight-70)/(bottom-top)));pan={x:(viewport.clientWidth-(right-left)*zoom)/2-left*zoom,y:(viewport.clientHeight-(bottom-top)*zoom)/2-top*zoom};paint();}
function zoomAt(next,x=viewport.clientWidth/2,y=viewport.clientHeight/2){next=Math.max(.15,Math.min(2.5,next));pan={x:x-(x-pan.x)*next/zoom,y:y-(y-pan.y)*next/zoom};zoom=next;paint();}
function portLink(from,to){linkStart=null;if(from.table===to.table&&from.column===to.column){status('Выберите другой столбец.');return;}editRelation(null,{parent:from.table,parentColumn:from.column,child:to.table,childColumn:to.column});}
viewport.onpointerdown=e=>{
 if(e.button!==0)return;const port=e.target.closest('[data-port]'),t=e.target.closest('[data-table]'),n=e.target.closest('[data-note]'),r=e.target.closest('[data-relation]');
 viewport.focus({preventScroll:true});
 if(port){gesture={kind:'link',from:{table:port.dataset.portTable,column:port.dataset.port},point:localPoint(e),startX:e.clientX,startY:e.clientY,moved:false};}
 else if(t||n){const id=t?.dataset.table||n.dataset.note,item=model.tables.find(t=>t.id===id)||model.notes.find(n=>n.id===id);selection=id;gesture={kind:'item',item,before:snapshot(),x:item.x,y:item.y,startX:e.clientX,startY:e.clientY,moved:false};render();}
 else if(r){selection=r.dataset.relation;render();gesture=null;}
 else {selection=null;gesture={kind:'pan',x:pan.x,y:pan.y,startX:e.clientX,startY:e.clientY,moved:false};render();}
 if(gesture){viewport.setPointerCapture(e.pointerId);e.preventDefault();}
};
viewport.onpointermove=e=>{
 if(!gesture)return;const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;gesture.moved ||= Math.abs(dx)+Math.abs(dy)>4;
 if(!gesture.moved)return;
 if(gesture.kind==='item'){gesture.item.x=Math.max(-50000,Math.min(50000,Math.round((gesture.x+dx/zoom)/10)*10));gesture.item.y=Math.max(-50000,Math.min(50000,Math.round((gesture.y+dy/zoom)/10)*10));paint();}
 if(gesture.kind==='pan'){pan={x:gesture.x+dx,y:gesture.y+dy};paint();}
 if(gesture.kind==='link'){svg.querySelector('[data-link-preview]')?.remove();const p=localPoint(e);svg.querySelector('[data-scene]').append(node('path',{'data-link-preview':'',d:`M ${gesture.point.x} ${gesture.point.y} L ${p.x} ${p.y}`,class:'design-edge-line','stroke-dasharray':'6 4','pointer-events':'none'}));}
};
viewport.onpointerup=safe(e=>{
 const g=gesture;gesture=null;if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);if(!g)return;
 if(g.kind==='item')commit(g.before);
 if(g.kind==='link'){svg.querySelector('[data-link-preview]')?.remove();if(!g.moved){if(linkStart)portLink(linkStart,g.from);else{linkStart=g.from;status('Теперь нажмите кружок у дочернего столбца или Escape для отмены.');}}else{const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-port]');if(target)portLink(g.from,{table:target.dataset.portTable,column:target.dataset.port});else status('Перетащите связь на кружок у дочернего столбца.');}}
});
viewport.onpointercancel=()=>{if(gesture?.kind==='item'){const old=JSON.parse(gesture.before);model=old.model;name=old.name;}gesture=null;paint();};
viewport.ondblclick=safe(e=>{if(e.target.closest('[data-port]'))return;const t=e.target.closest('[data-table]'),n=e.target.closest('[data-note]');if(t)editTable(model.tables.find(x=>x.id===t.dataset.table));else if(n)editNote(model.notes.find(x=>x.id===n.dataset.note));else if(!e.target.closest('[data-relation]'))newTable(localPoint(e));});
viewport.addEventListener('wheel',e=>{e.preventDefault();const b=viewport.getBoundingClientRect();zoomAt(zoom*Math.exp(-e.deltaY*.001),e.clientX-b.left,e.clientY-b.top);},{passive:false});
function historyStep(back){const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;to.push(snapshot());const s=JSON.parse(from.pop());model=s.model;name=s.name;selection=null;draft();render();}
viewport.onkeydown=safe(e=>{if(e.key==='Escape'){linkStart=null;status();return;}if(e.key==='Enter'){const port=e.target.closest('[data-port]');if(port){const to={table:port.dataset.portTable,column:port.dataset.port};if(linkStart)portLink(linkStart,to);else{linkStart=to;status('Выберите дочерний столбец клавишей Enter.');}return;}const t=e.target.closest('[data-table]'),r=e.target.closest('[data-relation]'),n=e.target.closest('[data-note]');selection=t?.dataset.table||r?.dataset.relation||n?.dataset.note;render();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const dx=e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0,dy=e.key==='ArrowUp'?-10:e.key==='ArrowDown'?10:0,item=[...model.tables,...model.notes].find(i=>i.id===selection);if(item)update(()=>{item.x+=dx;item.y+=dy;});else{pan.x+=dx;pan.y+=dy;paint();}}});
document.addEventListener('keydown',e=>{if(panel.hidden||$('modal').open||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();historyStep(!e.shiftKey);}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected();}});
$('design-name').onchange=()=>{const value=$('design-name').value.trim();if(!value){$('design-name').value=name;return;}update(()=>{name=value;});};
$('design-table').onclick=safe(()=>newTable());$('design-link').onclick=safe(()=>editRelation());$('design-note').onclick=()=>{const n={id:uid(),text:'Заметка к модели',x:(70-pan.x)/zoom,y:(90-pan.y)/zoom};update(()=>{model.notes.push(n);selection=n.id;});editNote(n);};
$('design-undo').onclick=()=>historyStep(true);$('design-redo').onclick=()=>historyStep(false);$('design-fit').onclick=fit;$('design-plus').onclick=()=>zoomAt(zoom*1.2);$('design-minus').onclick=()=>zoomAt(zoom/1.2);
$('design-fullscreen').onclick=safe(async()=>{if(document.fullscreenElement===panel)await document.exitFullscreen();else await panel.requestFullscreen();fit();});
$('design-new').onclick=safe(()=>discardThen(()=>replace(emptyDesign(),'Новый проект')));
async function saveProject(copy=false){
 if(saving)return;const capture=snapshot(),current=project,body={name,model:validateDesign(model),revision:project?.revision};saving=true;status();
 try{const p=await api(current&&!copy?'/api/designs/'+current.id:'/api/designs',{method:current&&!copy?'PUT':'POST',body});project={id:p.id,revision:p.revision};saved=capture;draft();status('Проект сохранён в Studio'+(changed()?' · новые изменения ещё не сохранены':''));}
 catch(e){notice(e.message,true);if(e.details?.error?.includes('другом окне'))status('Конфликт сохранения. В «Открыть…» можно сохранить отдельную копию.');}finally{saving=false;$('design-save').disabled=false;}
}
$('design-save').onclick=safe(()=>saveProject());
$('design-open').onclick=safe(async()=>{
 if(saving)throw new Error('Дождитесь сохранения.');const items=await api('/api/designs');
 modal('Проекты конструктора',`<button type="button" class="button" id="design-save-copy">Сохранить текущий проект отдельной копией</button><div>${items.map(p=>`<div class="object-row"><button type="button" class="history-item" data-design-open="${p.id}"><strong>${esc(p.name)}</strong><small>${p.tables} таблиц · ${new Date(p.updatedAt).toLocaleString('ru-RU')}</small></button><button type="button" class="button danger" data-design-remove="${p.id}">Удалить</button></div>`).join('')||'<p>Сохранённых проектов пока нет.</p>'}</div>`,async()=>{},'Закрыть',false,true);
 $('design-save-copy').onclick=safe(async()=>{$('modal').close();await saveProject(true);});
 const listener=safe(async e=>{const open=e.target.closest('[data-design-open]'),remove=e.target.closest('[data-design-remove]');if(open){const p=await api('/api/designs/'+open.dataset.designOpen);$('modal').close();discardThen(()=>replace(p.model,p.name,{id:p.id,revision:p.revision}));}if(remove){const p=items.find(p=>p.id===remove.dataset.designRemove);$('modal').close();confirmAction('Удалить сохранённый проект',p.name,async confirm=>{await api('/api/designs/'+p.id,{method:'DELETE',body:{confirm,revision:p.revision}});if(project?.id===p.id){project=null;saved='';draft();status();}notice('Сохранённый проект удалён.');},'Удаляется проект схемы. Базы данных не изменяются.');}});
 $('modal-body').addEventListener('click',listener);$('modal').addEventListener('close',()=>$('modal-body').removeEventListener('click',listener),{once:true});
});
$('design-json').onclick=()=>download(JSON.stringify({name,model},null,2),name+'.dbdesign.json','application/json');
$('design-import').onclick=()=>{modal('Импорт проекта','<label class="field">JSON проекта Studio<input type="file" name="file" accept=".json,application/json" required></label><p class="muted">Текущий черновик будет заменён. Формат .drawio не поддерживается.</p>',async form=>{if(saving)throw new Error('Дождитесь сохранения.');const file=form.elements.file.files[0];if(!file||file.size>2*1024*1024)throw new Error('Выберите JSON-файл не больше 2 МБ.');const imported=JSON.parse(await file.text());if(typeof imported.name!=='string'||!imported.name.trim()||imported.name.length>120)throw new Error('Некорректное название проекта.');replace(validateDesign(imported.model),imported.name);},'Импортировать',false,true);};
$('design-sql').onclick=safe(()=>{
 const result=designSQL(model);modal('SQL проекта',result.errors.length?'<h3>Перед экспортом исправьте</h3><ul>'+result.errors.map(e=>'<li>'+esc(e)+'</li>').join('')+'</ul>':result.warnings.map(w=>'<p class="query-warning">'+esc(w)+'</p>').join('')+`<p class="muted">Создаются только таблицы и FK. Циклы с NO ACTION допустимы; каскадные пути, размеры ключей и специальные ограничения дополнительно проверяет SQL Server.</p><pre class="sql-preview">${esc(result.sql)}</pre><button type="button" class="button" id="design-sql-download">Скачать .sql</button>`,async()=>{},'Закрыть',false,true);if(!result.errors.length)$('design-sql-download').onclick=()=>download(result.sql,name+'.sql');
});
$('design-svg-export').onclick=safe(()=>{
 const clone=svg.cloneNode(true),scene=clone.querySelector('[data-scene]');scene.removeAttribute('transform');clone.querySelector('rect[width="100%"]')?.remove();const items=[...model.tables.map(t=>({...t,w:W,h:height(t)})),...model.notes.map(n=>({...n,w:250,h:230}))];const left=Math.min(0,...items.map(t=>t.x))-150,top=Math.min(0,...items.map(t=>t.y))-100,right=Math.max(300,...items.map(t=>t.x+t.w))+150,bottom=Math.max(200,...items.map(t=>t.y+t.h))+100;clone.setAttribute('viewBox',`${left} ${top} ${right-left} ${bottom-top}`);clone.setAttribute('width',right-left);clone.setAttribute('height',bottom-top);
 const style=node('style');style.textContent=svgCSS;clone.prepend(style);const computed=getComputedStyle(document.documentElement);for(const v of ['--surface','--ink','--line','--blue','--blue-soft','--muted','--warning-bg','--warning','--soft-line'])clone.style.setProperty(v,computed.getPropertyValue(v));clone.style.background=computed.getPropertyValue('--bg');download(new XMLSerializer().serializeToString(clone),name+'.svg','image/svg+xml');
});
const svgCSS=`text{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:12px;fill:var(--ink)}.design-table-body{fill:var(--surface);stroke:var(--line);stroke-width:1.5}.design-table-header{fill:var(--blue-soft)}.design-title{font-size:14px;font-weight:600}.design-divider{stroke:var(--soft-line)}.design-key{font-size:10px;fill:var(--blue);font-weight:600}.design-type{font-size:10px;fill:var(--muted)}.design-column{font-size:11px}.design-port{fill:var(--surface);stroke:var(--blue);stroke-width:2;cursor:crosshair}.design-port:hover,.design-port:focus{fill:var(--blue);r:7px}.design-edge-line{fill:none;stroke:var(--blue);stroke-width:1.8}.design-edge-hit{fill:none;stroke:transparent;stroke-width:14}.design-edge-label{font-size:11px;fill:var(--muted);paint-order:stroke;stroke:var(--surface);stroke-width:4;stroke-linejoin:round}.design-edge{cursor:pointer}.design-table,.design-note{cursor:grab;outline:none}.design-table.selected .design-table-body,.design-table:focus .design-table-body{stroke:var(--blue);stroke-width:3}.design-edge.selected .design-edge-line{stroke-width:3.5}.design-note rect{fill:var(--warning-bg);stroke:var(--warning);stroke-width:1}.design-note.selected rect{stroke-width:3}.design-note text{fill:var(--warning)}`;
const style=document.createElement('style');panel.append(style);
// CSS is scoped with a stylesheet rule per selector; exported SVG uses the same declarations.
style.textContent=svgCSS.replace(/(^|})([^{}]+)\{/g,(_,start,selectors)=>start+selectors.split(',').map(s=>'#design-svg '+s.trim()).join(',')+'{');
try{const cached=JSON.parse(localStorage.getItem('studio.designer.draft.v1')||'null');if(cached){model=validateDesign(cached.model);if(typeof cached.name==='string'&&cached.name.trim()&&cached.name.length<=120)name=cached.name;project=cached.project?.id&&Number.isInteger(cached.project.revision)?cached.project:null;saved=typeof cached.saved==='string'?cached.saved:'';}}catch{notice('Черновик конструктора не удалось восстановить. Сохранённые проекты доступны в «Открыть…».',true);}
window.addEventListener('beforeunload',e=>{if(changed()&&(model.tables.length||model.notes.length)){e.preventDefault();e.returnValue='';}});
document.addEventListener('workspace-tab-changed',e=>{if(e.detail==='designer'){render();if(zoom===1&&pan.x===30&&pan.y===30)fit();}});
render();
